version: '3.1'
services:

npm_app:
image: jc21/nginx-proxy-manager:latest
container_name: npm_app
restart: always
ports:
- '80:80'
- '81:81'
- '443:443'
environment:
DB_MYSQL_HOST: "npm_db"
DB_MYSQL_PORT: 3306
DB_MYSQL_USER: "npm"
DB_MYSQL_PASSWORD: "npm"
DB_MYSQL_NAME: "npm"
volumes:
- ./npm/data:/data
- ./npm/letsencrypt:/etc/letsencrypt
depends_on:
- npm_db
networks:
main_stack:
ipv4_address: 10.5.0.2

npm_db:
image: jc21/mariadb-aria:latest
container_name: npm_db
restart: always
environment:
MYSQL_ROOT_PASSWORD: 'npm'
MYSQL_DATABASE: 'npm'
MYSQL_USER: 'npm'
MYSQL_PASSWORD: 'npm'
volumes:
- ./npm/data/mysql:/var/lib/mysql
networks:
main_stack:
ipv4_address: 10.5.0.3
